version: "3"
services:
  mongodb:
    container_name: worker-mongodb
    hostname: worker-mongodb
    image: "mongo:6"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"
    env_file:
      - .env
